services:
    # Laravel Application
    app:
        image: webdevops/php-nginx:8.3-alpine
        container_name: app
        working_dir: /app
        command: sh -c ".deploy/run.sh && nginx -g 'daemon off;'"
        ports:
            - "8010:80"
        volumes:
            - .:/app
            - composer_cache:/root/.composer/cache
            - .deploy/conf/nginx/default.conf:/opt/docker/etc/nginx/vhost.conf
        depends_on:
            - mysql
        networks:
            - app_net
        environment:
            - APP_ENV=local
            - APP_DEBUG=true

    # MySQL Database
    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app_db
            MYSQL_USER: app_user
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app_net
        command: --default-authentication-plugin=mysql_native_password

    # phpMyAdmin for Database Management
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: secret
        depends_on:
            - mysql
        networks:
            - app_net

volumes:
    composer_cache:
    mysql_data:

networks:
    app_net:
        driver: bridge
